title: "Dwayne | Fitness Journey"
description: "Dwayne's Fitness Journey - Workout logs, progress updates, and gym motivation"
logo: "DWAYNE"
tagline: "Discipline • Strength • Growth"
heroTitle: "DWAYNE'S"
heroHighlight: "FITNESS JOURNEY"
heroSubtitle: "Chasing 190. Building strength. Documenting every rep, every set, every victory."

social:
  instagram: "#"
  tiktok: "#"
  youtube: "#"

footer:
  tagline: "Chasing PRs, one rep at a time."
  copyright: "© 2026 Dwayne. All rights reserved. Built with 💪"
